export enum ActionTypes {
	ADD_USER = 'ADD_USER',

	LOGOUT = 'LOGOUT',
	LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
	LOGOUT_FAILURE = 'LOGOUT_FAILURE',

	FETCH_USER = 'FETCH_USER',
	FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',
	FETCH_USER_FAILURE = 'FETCH_USER_FAILURE',
}
