export enum ActionTypes {
	LOAD_AUTHORS = 'LOAD_AUTHORS',
	DELETE_AUTHOR = 'DELETE_AUTHOR',

	CREATE_AUTHOR = 'CREATE_AUTHOR',
	CREATE_AUTHORS_SUCCESS = 'CREATE_AUTHORS_SUCCESS',
	CREATE_AUTHORS_FAILURE = 'CREATE_AUTHORS_FAILURE',

	FETCH_AUTHORS = 'FETCH_AUTHORS',
	FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS',
	FETCH_AUTHORS_FAILURE = 'FETCH_AUTHORS_FAILURE',
}
